### ISSUE TITLE
Being muted for divulge the server itself

### ISSUE THREAD

**Issue by costaluu** [yagomichalak/sloth-bot#14]
Could you include an exception to prevent people from being muted by divulge the server itself? In particular the link `https://discord.gg/languages`

https://github.com/yagomichalak/sloth-bot/blob/df5abb42d9330e15aa71cfbac0b356db6ef3e541/cogs/moderation.py#L51-L60

**Comment by yagomichalak** [comment]
Yeah, I don't see why a user would need to use the invite of the server within the server, but I'll add this anyways.
